### ISSUE TITLE
flutter_sound 9.6.0 ios play errror

### ISSUE THREAD

**Issue by weixin95827** [Canardoux/tau#1]
import 'package:flutter/material.dart';
import 'package:flutter_sound/flutter_sound.dart';
import 'package:permission_handler/permission_handler.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Sound Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  FlutterSoundRecorder _recorder = FlutterSoundRecorder();
  FlutterSoundPlayer _player = FlutterSoundPlayer();
  bool _isRecording = false;
  bool _isPlaying = false;
  String _filePath = 'audio_example.aac';

  @override
  void initState() {
    super.initState();
    _initialize();
  }

  Future<void> _initialize() async {
    await _recorder.openRecorder();
    await _player.openPlayer();
    await _checkPermissions();
  }

  Future<void> _checkPermissions() async {
    if (await Permission.microphone.request().isGranted) {
      // Microphone permission granted
    } else {
      // Microphone permission denied
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Microphone permission is required to record audio.'),
        ),
      );
    }
  }

  Future<void> _startRecording() async {
    if (await Permission.microphone.isGranted) {
      try {
        await _recorder.startRecorder(
          toFile: _filePath,
          codec: Codec.aacMP4,
        );
        setState(() {
          _isRecording = true;
        });
      } catch (e) {
        print('Failed to start recording: $e');
      }
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Microphone permission is required to record audio.'),
        ),
      );
    }
  }

  Future<void> _stopRecording() async {
    try {
      await _recorder.stopRecorder();
      setState(() {
        _isRecording = false;
      });
    } catch (e) {
      print('Failed to stop recording: $e');
    }
  }

  Future<void> _startPlaying() async {
    try {
      await _player.startPlayer(
        fromURI: _filePath,
        codec: Codec.aacMP4,
      );
      setState(() {
        _isPlaying = true;
      });
    } catch (e) {
      print('Failed to start playing: $e');
    }
  }

  Future<void> _stopPlaying() async {
    try {
      await _player.stopPlayer();
      setState(() {
        _isPlaying = false;
      });
    } catch (e) {
      print('Failed to stop playing: $e');
    }
  }

  @override
  void dispose() {
    _recorder.closeRecorder();
    _player.closePlayer();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Sound Demo'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: _isRecording ? _stopRecording : _startRecording,
              child: Text(_isRecording ? 'Stop Recording' : 'Start Recording'),
            ),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: _isPlaying ? _stopPlaying : _startPlaying,
              child: Text(_isPlaying ? 'Stop Playing' : 'Start Playing'),
            ),
          ],
        ),
      ),
    );
  }
}

pubspec:
dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.6.0
  permission_handler: ^10.2.0

Android can play it normally, but iOS fails to play it. I don't know what happened.

**Comment by weixin95827** [comment]
override

**Comment by Larpoux** [comment]
@weixin95827 
You probably forgot to open an audio session. This is very important on ios. I am going for lunch. I will try to help you after lunch

**Comment by weixin95827** [comment]
> @weixin95827 You probably forgot to open an audio session. This is very important on ios. I am going for lunch. I will try to help you after lunch

Thank you very much, I will pay attention to the possibility you mentioned。

**Comment by Larpoux** [comment]
@weixin95827 
Did you solve your issue?
The documentation is not uptodate.
You must open an audio session using [https://pub.dev/packages/audio_session](https://pub.dev/packages/audio_session).
You can look to the [simple recorder](flutter_sound/example/lib/simple_recorder)
```dart
final session = await AudioSession.instance;
    await session.configure(AudioSessionConfiguration(
      avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
      avAudioSessionCategoryOptions:
          AVAudioSessionCategoryOptions.allowBluetooth |
              AVAudioSessionCategoryOptions.defaultToSpeaker,
      avAudioSessionMode: AVAudioSessionMode.spokenAudio,
      avAudioSessionRouteSharingPolicy:
          AVAudioSessionRouteSharingPolicy.defaultPolicy,
      avAudioSessionSetActiveOptions: AVAudioSessionSetActiveOptions.none,
      androidAudioAttributes: const AndroidAudioAttributes(
        contentType: AndroidAudioContentType.speech,
        flags: AndroidAudioFlags.none,
        usage: AndroidAudioUsage.voiceCommunication,
      ),
      androidAudioFocusGainType: AndroidAudioFocusGainType.gain,
      androidWillPauseWhenDucked: true,
    ));
    ```

**Comment by weixin95827** [comment]
> @weixin95827 你解决问题了吗？ 文档不是最新的。你必须使用https://pub.dev/packages/audio_session 打开音频会话。 你可以查看[简单的录音机](flutter_sound/example/lib/simple_recorder)[](https://pub.dev/packages/audio_session)[](flutter_sound/example/lib/simple_recorder)
> 
> ```dart
> final session = await AudioSession.instance;
>     await session.configure(AudioSessionConfiguration(
>       avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
>       avAudioSessionCategoryOptions:
>           AVAudioSessionCategoryOptions.allowBluetooth |
>               AVAudioSessionCategoryOptions.defaultToSpeaker,
>       avAudioSessionMode: AVAudioSessionMode.spokenAudio,
>       avAudioSessionRouteSharingPolicy:
>           AVAudioSessionRouteSharingPolicy.defaultPolicy,
>       avAudioSessionSetActiveOptions: AVAudioSessionSetActiveOptions.none,
>       androidAudioAttributes: const AndroidAudioAttributes(
>         contentType: AndroidAudioContentType.speech,
>         flags: AndroidAudioFlags.none,
>         usage: AndroidAudioUsage.voiceCommunication,
>       ),
>       androidAudioFocusGainType: AndroidAudioFocusGainType.gain,
>       androidWillPauseWhenDucked: true,
>     ));
>     ```
> ```

Yes, this solved my problem, thank you very much!
