### ISSUE TITLE
Error with Manifest File

### ISSUE THREAD

**Issue by lettaz** [Canardoux/tau#1]
Hello there,

I love your project and your awesome plugin but when i want to implement it i get this on build.

Error:
	android:exported needs to be explicitly specified for element <service#com.dooboolab.TauEngine.FlautoBackgroundAudioService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
Error:
	android:exported needs to be explicitly specified for element <receiver#androidx.media.session.MediaButtonReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by Larpoux** [comment]
Flutter Sound needs [Android 21 or later](https://flutter-sound.canardoux.xyz/readme.html#sdk-requirements)
and set yourApp/android/app/build.gradle correctly.
You can look to [the provided example](https://github.com/Canardoux/flutter_sound/blob/master/flutter_sound/example/android/app/build.gradle).

**Comment by Larpoux** [comment]
Of course you must upgrade your android SDK to a recent version

**Comment by lettaz** [comment]
Hi there, thanks for the prompt response,

Yeah i know that it needs Android 21 and higher, my setup is structured to work with Android 34.
 compileSdkVersion 34
 minSdkVersion 21
 targetSdkVersion 34
 
This is my gradle configuration and i get that error.

It basically said if i am targeting Android 12(API level 31 and above) and higher i need to have that android:exported on the service and reciever in the manifest file but i can't find them.

**Comment by Larpoux** [comment]
Maybe the problem is with your gradle version. Flutter really likes very recent versions of gradle.

**Comment by Larpoux** [comment]
Perhaps you should update Android SDK (it is very simple on Android Studio) and run "flutter doctor"
