### ISSUE TITLE
[enh] Change speed playback

### ISSUE THREAD

**Issue by fzyzcjy** [Canardoux/tau#382]
**Is your feature request related to a problem? Please describe.**
Hi thanks for the library! I wonder whether we can change the speed of audio, or we also need to use libraries like ffmpeg? Thanks!

It seems that both Android and iOS have native APIs, so maybe it can be easily done? :)
ref: https://stackoverflow.com/questions/42903516/android-studio-changing-playback-speed-of-audio-for-api23
ref: https://stackoverflow.com/questions/2427821/iphone-sdk-change-playback-speed-using-core-audio-avaudioplayer

**Comment by fzyzcjy** [comment]
@Larpoux (or anyone related) Will you accept PR if I migrate it?

**Comment by Larpoux** [comment]
Hi @fzyzcjy .
Sure 💯  . Of course we will consider your PR if you submit one. Flutter Sound is actually in bad state because nobody is ready to collaborate. *We really need contributors*.
If you are ready to help Flutter Sound being a better plugin, we will be grateful.
Thank you so much if you can help 👍 💯

**Comment by Larpoux** [comment]
@fzyzcjy : I am currently working on an App which makes heavy use of sound.
My client asked me if it was possible to change the speed of audio, and I answered that it was not possible.
I would be very glad if I was wrong and if it is technically possible.
And my client will be happy, too.

**Comment by fzyzcjy** [comment]
@Larpoux IMHO it is definitely possible because of two reasons:

1. Native android/ios has apis: https://stackoverflow.com/questions/42903516/android-studio-changing-playback-speed-of-audio-for-api23 and https://stackoverflow.com/questions/2427821/iphone-sdk-change-playback-speed-using-core-audio-avaudioplayer
2. A competitive plugin: https://github.com/luanpotter/audioplayers has the feature (see: https://github.com/luanpotter/audioplayers/issues/557)

**Comment by Larpoux** [comment]
That should be really great 👍

**Comment by Larpoux** [comment]
@fzyzcjy : I plan to work a little bit on FS in a few weeks.
I am really excited by your proposition to add a way to control the playback speed.

Please tell me if you prefer to work yourself on this improvement or if you prefer that I work myself on this, following your advices with your two web links.
- If you plan to work yourself, this is great. There is no urgency waiting your PR. 
- If you prefer that I work myself on this improvement, this is OK, too. 

Just tell me.

**Comment by fzyzcjy** [comment]
@Larpoux I may not have time recently, and moreover, I have tried reading the source code but find it not very easy to understand... Thus maybe it is an easy task for you but challenging for people who are not familiar with your code.

**Comment by Larpoux** [comment]
OK @fzyzcjy , No problemo
Thank you very much to have tried to improve Flutter Sound. I appreciate very much when users feel concerned by Flutter Sound development.
I am going to look what I can do myself.

Have a nice day.

**Comment by Larpoux** [comment]
Registered in [the Flutter Sound Project](https://github.com/dooboolab/flutter_sound/projects/3)

**Comment by GGLabCenter** [comment]
A quick-and-dirty solution could be to double the frequency rate , so the time results divided by two then. If the recorded audio is 16khz, you can play at 32khz. This will result in a 2x speed, and so on for the other speeds.. it would be already possible (I did a test from an audio file) without mods to the lib.

**Comment by syedfaisaljaved** [comment]
Any solution to this issue?

**Comment by Larpoux** [comment]
[Flutter Sound 8.3.4](https://tau.canardoux.xyz/changelog.html) is released.
It includes [a new verb setSpeed](https://tau.canardoux.xyz/tau_api_player_set_speed.html).
@fzyzcjy : thank you for the links you wrote. They was useful.
