### ISSUE TITLE
[bug] AudioSource.voiceUplink

### ISSUE THREAD

**Issue by adityagautam98** [Canardoux/tau#430]
## Flutter Sound Version : 

- **Released**

- Version number - Flutter as well as this dependency is up to date.

- **FULL**

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)

----------------------------------------------------------

## Severity

- Crash

--------------------------------------------------------

## Platforms you faced the error 

- Android 

----------------------------------------------

## Logs
E/flutter (25450): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Exception: PlatformException(FlutterSoundRecorder, Error starting recorder, start failed.)
E/flutter (25450): #0      FlutterSoundRecorder.startRecorder (package:flutter_sound/src/flutter_sound_recorder.dart:315:7)
E/flutter (25450): <asynchronous suspension>
E/flutter (25450): #1      _HomePageState.recordAudio (package:nowcare4u_internal/HomePage/homePage.dart:145:28)
E/flutter (25450): <asynchronous suspension>
E/flutter (25450): #2      _HomePageState.build.<anonymous closure> (package:nowcare4u_internal/HomePage/homePage.dart:102:33)
E/flutter (25450): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (25450): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (25450): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (25450): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (25450): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (25450): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter (25450): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter (25450): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter (25450): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
E/flutter (25450): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (25450): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
E/flutter (25450): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
E/flutter (25450): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter (25450): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (25450): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (25450): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (25450): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (25450): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (25450): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (25450): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (25450): #23     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (25450): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
E/flutter (25450): 

------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**

**To Reproduce**

**Expected behavior**

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
Could you send the Android logs ?

**Comment by adityagautam98** [comment]
Yes, just a minute. Selecting audio source as AudioSource.voice_call is also causing similar issue. My application needs to record voice call (at least user side), I have mention Microphone and External Storage permissions in manifest. Is there any other config that I might be missing?

**Comment by Larpoux** [comment]
I am not sure that many Flutter Sound users know what is voiceUplink.
Did you try to set the microphone as input ?

I really need your Android logs, and not only the stack when crash

**Comment by adityagautam98** [comment]
Yes, I have tried microphone, but the recorded audio gets completely silent for the duration when user is on call i.e. nothing gets recorded. I really appreciate the quick help that your team is providing. When I am using source as voice call it is crashing.

**Comment by adityagautam98** [comment]
2020-08-11 21:38:41.909 25450-25507/com.nowcare4u.nowcare4u_internal I/flutter: Call is Incoming or Connectedtrue
2020-08-11 21:38:44.771 25450-29771/com.nowcare4u.nowcare4u_internal D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@b41b6ed[MainActivity]
2020-08-11 21:38:44.772 25450-25508/com.nowcare4u.nowcare4u_internal W/libEGL: EGLNativeWindowType 0x7bec1e7010 disconnect failed
2020-08-11 21:38:49.030 25450-25450/com.nowcare4u.nowcare4u_internal E/SensorManager: registerListenerImpl sensorName:lsm6dsm Accelerometer Non-wakeup,isWakeUpSensor:false,callingApp: com.nowcare4u.nowcare4u_internal,callingPid:25450,callingUid:10500
2020-08-11 21:38:49.094 25450-25450/com.nowcare4u.nowcare4u_internal E/MediaRecorder: start 0 mRotation
2020-08-11 21:38:49.121 25450-25450/com.nowcare4u.nowcare4u_internal E/MediaRecorder: start failed: -2147483648
2020-08-11 21:38:49.123 25450-25450/com.nowcare4u.nowcare4u_internal E/SoundMediaRecorder: Exception: 
    java.lang.RuntimeException: start failed.
        at android.media.MediaRecorder.native_start(Native Method)
        at android.media.MediaRecorder.start(MediaRecorder.java:1155)
        at com.dooboolab.fluttersound.FlutterSoundMediaRecorder._startRecorder(FlutterSoundMediaRecorder.java:150)
        at com.dooboolab.fluttersound.FlutterSoundRecorder.startRecorder(FlutterSoundRecorder.java:380)
        at com.dooboolab.fluttersound.FlautoRecorderPlugin.onMethodCall(FlutterSoundRecorder.java:114)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-08-11 21:38:49.127 25450-25450/com.nowcare4u.nowcare4u_internal E/MediaRecorder: resume called in an invalid state: 32
2020-08-11 21:38:49.127 25450-25450/com.nowcare4u.nowcare4u_internal E/MediaRecorder: stop called in an invalid state: 32
2020-08-11 21:38:49.127 25450-25450/com.nowcare4u.nowcare4u_internal D/SoundMediaRecorder: Error Stop Recorder
2020-08-11 21:38:49.129 25450-25450/com.nowcare4u.nowcare4u_internal D/OnePlusJankManager:  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = com.nowcare4u.nowcare4u_internal/com.nowcare4u.nowcare4u_internal.MainActivity--- jank level = 1
2020-08-11 21:38:49.141 25450-25507/com.nowcare4u.nowcare4u_internal E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Exception: PlatformException(FlutterSoundRecorder, Error starting recorder, start failed.)
    #0      FlutterSoundRecorder.startRecorder (package:flutter_sound/src/flutter_sound_recorder.dart:315:7)
    <asynchronous suspension>
    #1      _HomePageState.recordAudio (package:nowcare4u_internal/HomePage/homePage.dart:145:28)

**Comment by Larpoux** [comment]
I found (and fixed) a serious bug in Flutter Sound on Android, when the App tries to access its audio session (for example recording) just after opening his audio session. In some cases, the audio session is not yet fully initialized when the App does the [recording/playback] access.

The fix is on https://github.com/Canardoux/flauto
I have not yet done a pull request on Flutter Sound, because I do not have much spare time and I was not in a hurry because no Flutter Sound user has already complain about such a bug.
And I wanted to test the fix on my own App, before publishing it on Flutter Sound.

I am going, now, to look to your logs to see if this is related to this issue.

**Comment by Larpoux** [comment]
> Yes, I have tried microphone, but the recorded audio gets completely silent for the duration when user is on call i.e. nothing gets recorded. I really appreciate the quick help that your team is providing. When I am using source as voice call it is crashing.

But you do not have crash, when setting the microphone as input ?  Is that right ?

**Comment by Larpoux** [comment]
I think that not many users has already try to use voiceUplink. (not me ;-) )

If such users exist, probably good,  if they share their experience with you.
And someone should do some tests with this configuration (unfortunately not me :-(  )

If you discover something that Flutter Sound need to do to allow voiceUplink, please do a Pull Request.
We promise  that we will examine your PR carefully and implement it in Flutter Sound.

**Comment by adityagautam98** [comment]
> > Yes, I have tried microphone, but the recorded audio gets completely silent for the duration when user is on call i.e. nothing gets recorded. I really appreciate the quick help that your team is providing. When I am using source as voice call it is crashing.
> 
> But you do not have crash, when setting the microphone as input ? Is that right ?

Yes, microphone as input is working perfectly, unfortunately it is not recording anything while user is on call. Could you please suggest any work around for my use case where I need to record user's audio at least during call, I am stuck on this for a very long time since going native is not an option for me...   : )

**Comment by Larpoux** [comment]
I will do some test during the next weeks. It will be good if FS V6.0 fixes this issue

**Comment by Larpoux** [comment]
Registered in [the Flutter Sound Project](https://github.com/dooboolab/flutter_sound/projects/3)

**Comment by KingAlawaka** [comment]
Any fix to the problem? 
Unhandled Exception: Exception: Recorder is not open
E/flutter (18083): #0      FlutterSoundRecorder._waitOpen (package:flutter_sound/public/flutter_sound_recorder.dart:299:7)
E/flutter (18083): #1      FlutterSoundRecorder._startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:606:11)
E/flutter (18083): #2      FlutterSoundRecorder.startRecorder.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:583:13)
E/flutter (18083): #3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter (18083): #4      FlutterSoundRecorder.startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:582:17)
E/flutter (18083): #5      _CommentViewState.initState (package:vloggy/comment_view.dart:56:20)
E/flutter (18083): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (18083): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (18083): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (18083): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (18083): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (18083): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (18083): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (18083): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (18083): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (18083): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (18083): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (18083): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (18083): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (18083): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (18083): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (18083): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (18083): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (18083): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (18083): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (18083): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (18083): #26     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (18083): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (18083): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (18083): #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (18083): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (18083): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (18083): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (18083): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (18083): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (18083): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (18083): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (18083): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (18083): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (18083): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (18083): #40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (18083): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (18083): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (18083): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (18083): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:

**Comment by acamue** [comment]
> Any fix to the problem?
> Unhandled Exception: Exception: Recorder is not open
> E/flutter (18083): #0 FlutterSoundRecorder._waitOpen (package:flutter_sound/public/flutter_sound_recorder.dart:299:7)
> E/flutter (18083): #1 FlutterSoundRecorder._startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:606:11)
> E/flutter (18083): #2 FlutterSoundRecorder.startRecorder. (package:flutter_sound/public/flutter_sound_recorder.dart:583:13)
> E/flutter (18083): #3 BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
> E/flutter (18083): #4 FlutterSoundRecorder.startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:582:17)
> E/flutter (18083): #5 _CommentViewState.initState (package:vloggy/comment_view.dart:56:20)
> E/flutter (18083): #6 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
> E/flutter (18083): #7 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
> E/flutter (18083): #8 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
> E/flutter (18083): #9 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
> E/flutter (18083): #10 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
> E/flutter (18083): #11 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
> E/flutter (18083): #12 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
> E/flutter (18083): #13 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
> E/flutter (18083): #14 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
> E/flutter (18083): #15 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
> E/flutter (18083): #16 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
> E/flutter (18083): #17 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
> E/flutter (18083): #18 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
> E/flutter (18083): #19 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
> E/flutter (18083): #20 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
> E/flutter (18083): #21 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
> E/flutter (18083): #22 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
> E/flutter (18083): #23 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
> E/flutter (18083): #24 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
> E/flutter (18083): #25 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
> E/flutter (18083): #26 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
> E/flutter (18083): #27 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
> E/flutter (18083): #28 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
> E/flutter (18083): #29 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
> E/flutter (18083): #30 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
> E/flutter (18083): #31 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
> E/flutter (18083): #32 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
> E/flutter (18083): #33 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
> E/flutter (18083): #34 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
> E/flutter (18083): #35 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
> E/flutter (18083): #36 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
> E/flutter (18083): #37 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
> E/flutter (18083): #38 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
> E/flutter (18083): #39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
> E/flutter (18083): #40 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
> E/flutter (18083): #41 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
> E/flutter (18083): #42 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
> E/flutter (18083): #43 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
> E/flutter (18083): #44 ComponentElement.mount (package:flutter/src/widgets/framework.dart:

any solution???

**Comment by Larpoux** [comment]
Talha Yücel,

You sent me a private email saying that you have a problem with a tomorrow Deadline !!!
I am going to look what I can do during a so little elapsed time.

First : are you building something on iOS, Android or both (I mean for tomorrow !)

**Comment by Larpoux** [comment]
Talha Yücel,

My project is to support various `"input nodes"` in the future.
Specially **Web Codecs**, Sequencer, Sound Generators, and so on...

Of course not for tomorrow ;-)
I am going to see what is possible with this urgency.

What are you trying to do ?
- Record something
- Or playback something ?

What is your source ?

**Comment by yuceltalha** [comment]
Hello, first of all, I was very surprised and very happy to see your willingness to help.

I want to save the sound coming out of the application in a format in a music application using the flutter_sound library. The application will work on both iOS and Android platforms.

I don't know what to write to record the inner voice, but I understand how the rest of the functions of the library work.

Can you tell me what I should write in the audioSource section in this code sample?

`void record() {
    _mRecorder!
        .startRecorder(
      toFile: _mPath,
     // audioSource: AudioSource.voiceDownlink, 
    )
        .then((value) {
      setState(() {});
    });
  }`

**Comment by Larpoux** [comment]
I suggest to focus on just one platform to begin.
For example Android.

Let me allow 1 hour, to understand what is possible to do on Android.
Then I will post you something.

**Comment by yuceltalha** [comment]
> I suggest to focus on just one platform to begin.
> For example Android.
> 
> Let me allow 1 hour, to understand what is possible to do on Android.
> Then I will post you something.

wonderful! Waiting Impatiently. But unfortunately I don't have a mac device so I can't use multi-platform solutions.

**Comment by yuceltalha** [comment]
> I suggest to focus on just one platform to begin.
> For example Android.
> 
> Let me allow 1 hour, to understand what is possible to do on Android.
> Then I will post you something.

wonderful! Waiting Impatiently.

**Comment by Larpoux** [comment]
@yuceltalha ,

I have bad news for you : 

On Android we must have a very special permission to record UPLINK or DOWNLINK : 
```
 Manifest.permission.CAPTURE_AUDIO_OUTPUT
```

But this permission is _is reserved for use by system components and is not available to third-party applications._
Pleaser look to [this](https://developer.android.com/reference/android/media/MediaRecorder.AudioSource#VOICE_UPLINK)

I think that the problem is because it is illegal to record a communication in many countries.
Probably this stands also on iOS.
Actually I am unable to record DOWNLINK on my Xiaomi Chinese phone.

**Comment by yuceltalha** [comment]
> @yuceltalha ,
> 
> I have bad news for you :
> 
> On Android we must have a very special permission to record UPLINK or DOWNLINK :
> 
> ```
>  Manifest.permission.CAPTURE_AUDIO_OUTPUT
> ```
> 
> But this permission is _is reserved for use by system components and is not available to third-party applications._
> Pleaser look to [this](https://developer.android.com/reference/android/media/MediaRecorder.AudioSource#VOICE_UPLINK)
> 
> I think that the problem is because it is illegal to record a communication in many countries.
> Probably this stands also on iOS.
> Actually I am unable to record DOWNLINK on my Xiaomi Chinese phone.

Alright, do you think we can record internal audio in another software language? Or totally impossible?

**Comment by Larpoux** [comment]
I cannot be sure. I am not an expert. But it seems to me that Android (and probably iOS) dow not allow to record a communication.
Of course I can be wrong and it is possible that the problem in Flutter Sound is something else.

You can try others library. 
If you success, please tell me : it will mean that there is a bug in Flutter Sound.

Good luck for tomorrow. I would have really pleased to help you better.

**Comment by yuceltalha** [comment]
> I cannot be sure. I am not an expert. But it seems to me that Android (and probably iOS) dow not allow to record a communication.
> Of course I can be wrong and it is possible that the problem in Flutter Sound is something else.
> 
> You can try others libraries.
> If you success, please tell me : it will mean that there is a bug in Flutter Sound.
> 
> Good luck for tomorrow. I would have been really pleased to help you better.

I am thinking to use sounds library, but as I know sounds is better version of flutter_sound. Do you suggest use that library

**Comment by Larpoux** [comment]
No, not Sounds. It certainly will not be better. Sounds is an old fork from Flutter Sound and is not maintained.

Try instead a library which have many "Likes" and have a good Pub Score.

**Comment by yuceltalha** [comment]
> No, not Sounds. It certainly will not be better. Sounds is an old fork from Flutter Sound and is not maintained.
> 
> Try instead a library which has many "Likes" and has a good Pub Score.

Thank you, at least I have an excuse tomorrow :-D

I will try other libraries. I will let you know if I can fix it

**Comment by Larpoux** [comment]
Thanks. Good luck.
