### ISSUE TITLE
[enh] Seek before startPlayer()

### ISSUE THREAD

**Issue by SudoSharma** [Canardoux/tau#536]
**Describe the solution you'd like**
References #120. Would really love the ability to set seek position prior to starting player. 

Thank you for a wonderful package!

**Comment by Larpoux** [comment]
Hi @SudoSharma ,

This is certainly something that we will do. But I do not know when : there is many things to do and not enough developers.

But we will do it...

**Comment by Larpoux** [comment]
Registered in [the Flutter Sound Project](https://github.com/dooboolab/flutter_sound/projects/3)

**Comment by Larpoux** [comment]
Hi @SudoSharma ,

Flutter Sound [release 8.3.9](https://tau.canardoux.xyz/changelog.html) is released.
Now we can do a `seekToPlayer()` before starting the player.
