### ISSUE TITLE
[enh] Null Safety

### ISSUE THREAD

**Issue by jefrisingh** [Canardoux/tau#584]
## Flutter Sound Version : v7.4.14+1

- **FULL**

- Result of the command **"flutter pub deps | grep flutter_sound"**

$ flutter pub deps | grep flutter_sound
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65

$ flutter pub get
Because flutter_sound >=5.0.0 depends on intl ^0.16.1 and every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, flutter_sound >=5.0.0 is incompatible with flutter_localizations from sdk.
So, because project depends on both flutter_localizations any from sdk and flutter_sound ^7.4.14+1, version solving failed.
Running "flutter pub get" in project...                                  
pub get failed (1; So, because project depends on both flutter_localizations any from sdk and flutter_sound ^7.4.14+1, version solving failed.)

----------------------------------------------------------

## Severity
- Cannot build my App ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?

- Android ?

- **Both** ?

- Emulator ? 

- Real device ?

----------------------------------------------

## Logs
Because flutter_sound >=5.0.0 depends on intl ^0.16.1 and every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, flutter_sound >=5.0.0 is incompatible with flutter_localizations from sdk.

-----------------------------------------------------

**Describe the bug**
Can you please increase intl version to support nullsafety, because most of the other plugings intl version is increased , as described here we can't omit flutter localization package :(
-----------------------------------------------------------------

**Comment by Larpoux** [comment]
Yes, @jefrisingh .

I already had to fight with this error. This dependency is painful.
I am going to look what I can do this afternoon.

I will post here the result.

**Comment by jefrisingh** [comment]
Thanks for the quick support @Larpoux

**Comment by Larpoux** [comment]
@jefrisingh : 

intl 0.16.1 is the last released version of intl.
 0.17.0-nullsafety.2 is actually just a pre-release.

I do not think that it will be good for &tau; to depend on a pre-release version.
Other users will probably complain that "0.17.0-nullsafety.2" is not compatible with their own dependencies.

Am I wrong?

**Comment by Larpoux** [comment]
> and every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2,

I feel that Google did a mess in the Flutter dependencies.

**Comment by Larpoux** [comment]
The Flutter Sound dependency is : 
```
  intl: ^0.16.1
```
which means `>= 0.16.1 `
0.17.0-nullsafety.2 is not considered as `> 0.16.1` because it is just a pre-release.

Flutter Sound will automatically try to link 0.17.0 when this version will be released.
My thinking is that it is correct. But I do not understand how : 

> and every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2,

can be OK from Google. This is a mess. Really.

**Comment by jefrisingh** [comment]
@Larpoux Yes I aggree with you , we can't depend on pre-release let's wait for a stable release of intl:0.17.0 , Thanks for your time :+1:

**Comment by Larpoux** [comment]
intl is used by Flutter Sound to format the date in the Widget UI.
My thinking is that Widget UI is not good and uses too many dependencies without good reason.

It should be rewritten by someone (not me, I do not like this module).
This task is in the TODO list (#579)

**Comment by jefrisingh** [comment]
Okay, let me try to remove the Widget UI and add optional listening interface for timestame on FlutterSoundRecorder so the end user can formate the time how they want it, If succes I'll come here again with the solution

**Comment by Larpoux** [comment]
👍 💯  Great !!!

**Comment by Larpoux** [comment]
The Widget UI was coded by a very complicated guy.
Each time he has a simple problem he finds a very complicated solution.

I cut the code by half and removed 1/3 of the external dependencies which was not needed.
But this is still not good, and must be rewirtten.

**Comment by jefrisingh** [comment]
Hi quick update, I just downloaded the master repository and added it as my project dependency and commented intl on flutter_sound plugin pubspec.yaml now everything is working as expected. 
![image](https://user-images.githubusercontent.com/13378709/103812420-80199f00-5084-11eb-81c8-c7307d736db7.png)

**Comment by Larpoux** [comment]
GOOD 👍 
I will look tomorrow if this dependency is still needed by the Widget UI.
If this dependency is needed I will format the minute/seconds/milliseconds
without using intl.

good luck with your project, using &tau; 😄

**Comment by Larpoux** [comment]
OK @jefrisingh ,

I have just checked the &tau; code and you are right : 
I worked recently on this intl issue, and I removed the dependency (I have a bad memory, so I forgot that I already did it).

I am going to build a new Flutter Sound version, so that you will be able to use the official module on pub.org.

**Comment by jefrisingh** [comment]
This is awesome quick support @Larpoux , Thank you so much for your awsome work :+1:

**Comment by Larpoux** [comment]
Hi @jefrisingh ,

Flutter Sound 7.4.15 is released.
This version does not have any more a dependency to `intl`.

If you appreciate our user support, may I ask you to click on `thumb up` on top of [the pub.dev page](https://pub.dev/packages/flutter_sound) ?

Thank you. And come back if you have other problems.

**Comment by Larpoux** [comment]
Null Safety is now supported on v.8.0.0
