### ISSUE TITLE
[BUG]: Doesnt Play, Doesnt work

### ISSUE THREAD

**Issue by cyberpwnn** [Canardoux/tau#597]
## Flutter Sound Version : 

- **FULL** 

----------------------------------------------------------

## Severity

- Doesnt work

--------------------------------------------------------

## Platforms you faced the error 

- iOS Doesnt work

- Android Doesnt work

- Flutter Web Doesnt work

- Emulator Doesnt work

- Real device Doesnt work

------------------------------------------------

**Describe the bug**
Flutter sound does not play sound in flutter

**To Reproduce**
1. Follow the basic player setup instructions
2. Test it
3. Observe that flutter sound does not work on flutter
----------------------------------------------

# Logs
```
[        ] I/flutter (19296): FS:---> openAudioSession 
[   +7 ms] I/AudioManager(19296): In stopBluetoothSco(), calling application: care.myguide.app
[        ] I/AudioManager(19296): In setBluetoothScoOn(), on: false, calling application: care.myguide.app
[        ] I/AudioManager(19296): In setSpeakerphoneOn(), on: true, calling application: care.myguide.app
[   +5 ms] I/AudioManager(19296): In setSpeakerphoneOn(), on: true, calling application: care.myguide.app
[   +1 ms] I/AudioManager(19296): In setBluetoothScoOn(), on: false, calling application: care.myguide.app
[   +1 ms] I/AudioManager(19296): In stopBluetoothSco(), calling application: care.myguide.app
[        ] I/AudioManager(19296): In setMode(), mode: 0, calling application: care.myguide.app
[  +15 ms] I/flutter (19296): FS:---> channelMethodCallHandler : openAudioSessionCompleted
[        ] I/flutter (19296): FS:<--- channelMethodCallHandler : openAudioSessionCompleted
[  +69 ms] I/flutter (19296): FS:<--- openAudioSession 
[   +1 ms] I/flutter (19296): E: Failed to play audio! NoSuchMethodError: The getter 'uri' was called on null.
[        ] I/flutter (19296): Receiver: null
[        ] I/flutter (19296): Tried calling: uri
```

(they all look like this)

Is there a stable version that works with IOS and Android? I just need this for production and the two major audio players dont work anymore.

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
```
E: Failed to play audio! NoSuchMethodError: The getter 'uri' was called on null
```
This is probably something wrong in your code.
You should check if you try to access the method `uri` on an object which is null.
