### ISSUE TITLE
[enh] make licensing more clear regarding Tau React / GPL

### ISSUE THREAD

**Issue by rmgit** [Canardoux/tau#610]
**Is your feature request related to a problem? Please describe.**

The licensing is not 100% clear. 

https://github.com/Canardoux/tau/blob/master/flutter_sound/README.md says 
" 
- Flutter Sound is released under a license with a lesser copyleft clause: the LGPL-V3 license. This means that if you modify some of Flutter Sound code you must publish your modifications under the LGPL license too.
- Tau React is copyrighted by Canardoux (2021). 
- Tau React is released under a license with a strong copyleft clause : the GPL-V3 license. This means that if you use part or all of Tau React in your App, this App must be published under the GPL-V3 license, too.
"

There is no Tau React subfolder, but https://github.com/Canardoux/tau/tree/master/tau_core with lgpl v3.
To me it's not clear if any component in https://github.com/Canardoux/tau/ depends on or is part of Tau React. 

**Describe the solution you'd like**

Make the licensing  more clear.
- make clear if & where Tau React is used (and where the source is).
- If Tau React is not used in https://github.com/Canardoux/tau/ then remove the Tau React GPL-v3 caveat in the licensing texts in the repo and on https://pub.dev/packages/flutter_sound.  

**Describe alternatives you've considered**
I have briefly considered using the lib without caring and/or clearly understanding the licensing but decided against it :)

**Comment by Larpoux** [comment]
`tau_core` and Flutter Sound are both LGPL.

The future `tau-react` will be GPL.

**Comment by rmgit** [comment]
cool, thanks for the fast answer.

i think making that more explicit on the website and in the license text will help get more adoption.
i checked all the other packages first because of the caveat and because i couldn't recognize if it is relevant when using the flutter package.

**Comment by kanekv** [comment]
@Larpoux Is that the intent that no closed source apps can use flutter sound? With LGPL application should be accompanied with either source code or object files at time of install (if application is linked statically, which is what most apps do). This is pretty much impossible to implement correctly for closed source apps. We can't use any LGPL software because of it. I wonder if that was your intent. Thanks.

**Comment by Larpoux** [comment]
Flutter Sound (and tau_core) are LGPL for legacy reason : changing this license to GPL would be difficult and catastrophic for many actual Flutter Sound developers.

But new developments of software not directly linked with Flutter Sound (Estrela, tau_react, tau_editor, ...) will be GPL.
I consider LGPL as a [bad license](https://www.gnu.org/licenses/why-not-lgpl.en.html) and I really want to spend much time on GPL projects.
[See here](https://tau.canardoux.xyz/commento-post.html#the-license)
