### ISSUE TITLE
How Can I save the Media using custom path in WidgetUI Demo? #615[HELP]

### ISSUE THREAD

**Issue by Zangana** [Canardoux/tau#616]
For Flutter Web and Android. 
-------------------------------------

What I want is that to save the media in a specific path then save that path in a Database so, I can play it later.
I changed recordingFile to a specific path that I want to save the media didn't work, and I made the temFile return only a specific file still didn't work. I don't know where the media is saved.

Your help would be appreciated.

**Comment by Larpoux** [comment]
You did not specify if you run on Android iOS or Flutter Web.

I guess that you are on Flutter Web.
I am currently working on #592.
This issue will be fixed in 7.6.0, that I will release in some days, hopefully.

**Comment by Larpoux** [comment]
@Zangana ,

Flutter Sound 7.6.0 is released.
`stopRecorder()` now returns the URL of the recorded file. [see here](https://tau.canardoux.xyz/temporary_files.html).
It works on 
- iOS
- Android
- Flutter Web

**Comment by Zangana** [comment]
Will there be any updates for the example Wiget_UI? I can see every example have been updated except that one.
