### ISSUE TITLE
[BUG]: seekToPlayer can not work.

### ISSUE THREAD

**Issue by zxl777** [Canardoux/tau#623]
```
seekTo(int milliSecs) async {
   try {
      if (playerModule.isPlaying || playerModule.isPaused) {
        await playerModule.seekToPlayer(Duration(milliseconds: milliSecs));
      }
    } on Exception catch (err) {
      print('error: $err');
    }
  }
```
Test on Android

Only when seekTo(0) is normal, other values are not performed as expected.

**Comment by zxl777** [comment]
I found that this problem occurs when playing opus files.
`'https://static.v86.co/audiobook/MY5SatbZMAo/MY5SatbZMAo.webm';`

**Comment by zxl777** [comment]
opus (.webm) mkv format can not to seek.

opus(ogg) worked!

**Comment by Larpoux** [comment]
I am very glad that you solved your issue yourself 👍
