### ISSUE TITLE
[ENH]:upgrade mobile ffmpeg audio to version 4.4

### ISSUE THREAD

**Issue by zhangruiyu** [Canardoux/tau#634]
Hello, can you upgrade mobile ffmpeg audio to version 4.4
Because I need to convert the song to AMR WB format, but version 4.4.3 does not support this operation.
[https://github.com/tanersener/mobile-ffmpeg/issues/381](url)

**Comment by Larpoux** [comment]
Last Flutter Sound versions have ffmpeg 4.4 embedded.
You can use the flutter_FFmpeg plugin
