### ISSUE TITLE
Not playing audio on Android with minSdkVersion 29.

### ISSUE THREAD

**Issue by SanzharDev** [Canardoux/tau#646]
I'm having a problem, that I can't find a way to solve. I tried to add needed dependencies and give permission, tough it still not working on Android devices. There is no problem with iOS.
I'm trying to record audio on mic and then play it. Here is my code: 

`
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_sound/flutter_sound.dart';
import 'package:flutter_sound/public/flutter_sound_recorder.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';

class BottomControlPanelView extends StatefulWidget {
  @override
  _BottomControlPanelViewState createState() => _BottomControlPanelViewState();
}

class _BottomControlPanelViewState extends State<BottomControlPanelView> {
  FlutterSoundRecorder _myRecorder = FlutterSoundRecorder();
  FlutterSoundPlayer _myPlayer = FlutterSoundPlayer();
  bool _mRecorderIsInited = false;
  bool _mPlayerIsInited = false;

  @override
  Widget build(BuildContext context) {
    return Container(
        height: 150.0,
        child: Row(
          children: [
            IconButton(
              icon: Icon(Icons.mic),
              onPressed: _onPressedRecord,
            ),
            IconButton(
              icon: Icon(Icons.stop),
              onPressed: _onPressedStop,
            ),
            IconButton(
              icon: Icon(Icons.play_arrow_rounded),
              onPressed: _onPressedPlay,
            ),
          ],
        ));
  }

  @override
  void initState() {
    // Be careful : openAudioSession return a Future.
    // Do not access your FlutterSoundPlayer or FlutterSoundRecorder before the completion of the Future
    openTheRecorder().then((value) {
      setState(() {
        _mRecorderIsInited = true;
      });
    });
    _myPlayer.openAudioSession().then((value) {
      setState(() {
        _mPlayerIsInited = true;
      });
    });
    super.initState();
  }

  Future<void> openTheRecorder() async {
    var status = await Permission.microphone.request();
    if (status != PermissionStatus.granted) {
      throw RecordingPermissionException('Microphone permission nor granred');
    }
    await _myRecorder.openAudioSession();
    _mRecorderIsInited = true;
  }

  @override
  void dispose() {
    // Be careful : you must `close` the audio session when you have finished with it.
    _myRecorder.closeAudioSession();
    _myRecorder = null;
    _myPlayer.closeAudioSession();
    _myPlayer = null;
    super.dispose();
  }

  _onPressedRecord() async {
    Directory tempDir = await getTemporaryDirectory();
    String outputFile = '${tempDir.path}/myFile.aac';

    if (_mRecorderIsInited) {
      await _myRecorder.startRecorder(
        // codec: Codec.pcm16,
        toFile: outputFile,
        // sampleRate: 16000,
        // numChannels: 1,
      );
    }
  }

  _onPressedStop() async {
    await _myRecorder.stopRecorder();
  }

  _onPressedPlay() async {
    Directory tempDir = await getTemporaryDirectory();
    String outputFile = '${tempDir.path}/myFile.aac';
    if (_mPlayerIsInited) {
      await _myPlayer.startPlayer(
        fromURI: outputFile,
        // codec: Codec.pcm16,
        numChannels: 1,
        // sampleRate: 16000, // Used only with codec == Codec.pcm16
        whenFinished: () {
          setState(() {});
        },
      );
    }
  }
}
`

**also there is a pubspec.yaml:** 
`name: flutter_sound_trial
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.7.1 # audio player dependency
  flutter_sound: ^8.0.0+6 # audio recorder dependency
  path_provider: ^2.0.1
  permission_handler: ^6.1.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
  async: ^2.2.0
  sqflite: ^2.0.0+2
  path: ^1.8.0
  flutter_ffmpeg: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
`

I've tried to add ffmepg dependency and added line to the Gradle file, but still not playing me an audio. 
Could you tell me, where is the root of this problem?

**Comment by Larpoux** [comment]
> I've tried to add ffmepg dependency and added line to the Gradle file, but still not playing me an audio.

No, you do not have to include ffmpeg dependency.

> tough it still not working on Android devices.

You are not telling us what does not work : 
- the recorder ?
- the playback ?
- the build ?

```dart
if (_mRecorderIsInited) {
  await _myRecorder.startRecorder(
    // codec: Codec.pcm16,
    toFile: outputFile,
  );
}
```
You must specify the codec you want to use.
For example 'codec: Codec.aacADTS,

```dart
await _myPlayer.startPlayer(
fromURI: outputFile,
// codec: Codec.pcm16,
```
You must specify the codec you want to use.
For example 'codec: Codec.aacADTS,

Is the record file created ?
Where are your logs ??????????
