### ISSUE TITLE
[BUG]: error when using "openAudioSession", every second time

### ISSUE THREAD

**Issue by TobiGamer** [Canardoux/tau#648]
## Flutter Sound Version : 8.0.0+6

- **FULL** or **LITE** flavor: FULL

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
|-- flutter_sound 8.0.0+6
|   |-- flutter_sound_platform_interface 8.0.0+6
|   |-- flutter_sound_web 8.0.0+6
|   |   |-- flutter_sound_platform_interface...
----------------------------------------------------------

## Severity

Minor issue, error every second time "openAudioSession" is called (Only if App is used with Hot Relstart)
--------------------------------------------------------

## Platforms you faced the error 

- Android (Real Device)

------------------------------------------------

**Describe the bug**
If i test my app which uses the Recorder and need to use Hot Restart, then the Recorder wont work, if i Hot Restart again the Recorder will work again

**To Reproduce**
1. in init start audio session (openAudioSession)
2. Use Hot Restart
(3. closeAudioSession is in dispose, but probably doesnt matter for Hot Reload)
----------------------------------------------

# Logs!!!!
(**This is very important**. Most of the time we cannot do anything if we do not have information on your bug)

![error](https://user-images.githubusercontent.com/18483572/112041646-eb80f200-8b46-11eb-85be-1219ff5ed0a3.jpg)

-----------------------------------------------------------------

# Additional Remarks

I already checked your code for possible errors, that i could have caused, and I think I might have found where the issue resides.
in "tau/flutter_sound/android/src/main/java/com/dooboolab/fluttersound/FlutterSoundManager.java lines: 102-113
if in the file line 108 (the reset method) gets executed it uses "result.success ( "reset" ); " (FlutterSoundRecorder.java line: 148)
-> which is a string and thus cannot be converted to int (as indecated by my error log)

-----------------------------------------------------------------

**Comment by marcoberetta96** [comment]
I suggest to double check that you are triggering `playerModule.closeAudioSession()` also when you hot restart. This solved for me.

**Comment by yun-cheng** [comment]
> I suggest to double check that you are triggering `playerModule.closeAudioSession()` also when you hot restart. This solved for me.

I have the same problem using Simple Recorder in the example app after hot restart. How did you solve the problem?

**Comment by TobiGamer** [comment]
Are you running the newest version of the libary? The error describe in this Bug was fixed in version 8.1.4. I just tested the code I hade the problem with and it worked fine with the newest version of the library (8.1.9). You either need to use a newer version or maybe you have a different bug causing the same symtoms.

**Comment by Larpoux** [comment]
Thank you @TobiGamer  for having shared your experience.

Please re-open this issue if you encounter other problems
