### ISSUE TITLE
[BUG]: App doesn't build with the latest version

### ISSUE THREAD

**Issue by psrcek** [Canardoux/tau#658]
Flutter Sound Version : 8.0.1+11

Result of the command : ```flutter pub deps | grep flutter_sound```

```
|-- flutter_sound 8.0.1+11
|   |-- flutter_sound_platform_interface 8.0.1+11
|   |-- flutter_sound_web 8.0.1+11
|   |   |-- flutter_sound_platform_interface...
```

----------------------------------------------------------

## Severity

App does not build. Your artifact server seems to be broken.

--------------------------------------------------------

## Platforms you faced the error 

Android

------------------------------------------------

**Describe the bug**
Any app using your library doesn't build.

**To Reproduce**

Try to build an app with a clean flutter cache.

----------------------------------------------

# Logs

```
Running Gradle task 'bundleRelease'...                          
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:minifyReleaseWithR8'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve xyz.canardoux:tau_sound_core:8.0.1+11.
     Required by:
         project :app > project :flutter_sound
      > Could not resolve xyz.canardoux:tau_sound_core:8.0.1+11.
         > Could not get resource 'https://dl.bintray.com/larpoux/TauRepo/xyz/canardoux/tau_sound_core/8.0.1+11/tau_sound_core-8.0.1+11.pom'.
            > Could not GET 'https://dl.bintray.com/larpoux/TauRepo/xyz/canardoux/tau_sound_core/8.0.1+11/tau_sound_core-8.0.1+11.pom'. Received status code 502 from server: Bad Gateway
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 2m 35s
```

-----------------------------------------------------------------

**Comment by psrcek** [comment]
That url now responds with a `403 Forbidden` error

**Comment by viniciusblecha** [comment]
im have the same issue

**Comment by barees63** [comment]
same

**Comment by marcoberetta96** [comment]
Same problem. The http request return a `403 forbidden error`

**Comment by psrcek** [comment]
Bintray is shutting down their services on may 1st. That was a planned brownout to remind people to switch away.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

![image](https://user-images.githubusercontent.com/13370323/114474595-d69ff780-9bf6-11eb-93a2-f4d9a5fc3635.png)

**Comment by marcoberetta96** [comment]
so I think the question is: will be the problem solved before May 1st?

**Comment by Larpoux** [comment]
Actually I am not working on Tau, and I have decided to let other developers maintain Tau.
(I have another project that is very late and on which I must work).

But this point is **VERY SERIOUS**. In two weeks **NOBODY WILL BE ABLE TO LINK THEIR APP, ANYMORE**.

So I think that I do not have any choice than fixing this issue before May 1st.
I am going to do that, now. But I really want other developers will maintain Tau.

**Comment by Larpoux** [comment]
Flutter Sound 8.1.1. is released and published on JitPack instead of Jfrog/bintray.
