### ISSUE TITLE
[HELP]: How to set Flutter Sound using ffmpeg 'full-gpl-lts'

### ISSUE THREAD

**Issue by winsonloh1998** [Canardoux/tau#661]
Since Flutter sound FULL using ffmpeg but not the full-gpl-lts, how can i pre-set the ffmpeg package to use full-gpl-lts' so that in my project, i still able to use the libx264 to compress my video.

`
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.arthenica.mobileffmpeg.Abi found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.AbiDetect found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.AsyncFFmpegExecuteTask found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.AsyncFFprobeExecuteTask found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.AsyncGetMediaInformationTask found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.BuildConfig found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.CameraSupport found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.Config found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.Config$1 found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.ExecuteCallback found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.FFmpeg found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.FFmpegExecution found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.FFprobe found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.GetMediaInformationCallback found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.Level found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.LogCallback found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.LogMessage found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.MediaInformation found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.MediaInformationParser found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.Packages found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.Signal found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.Statistics found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
  Duplicate class com.arthenica.mobileffmpeg.StatisticsCallback found in modules classes.jar (com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS) and classes.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS)
`

**Comment by Larpoux** [comment]
> ## Perhaps it is not the good place to request for help, here ?
> ## Perhaps you could consider using one of the _sharing_ channels ?
> ## For example the _Element_ τ room ?

Actually issues like this one is the good place. Element Tau room is stalled and not used.

Normally, you do not have to do anything to link with FFmpeg full library.
But it is not possible to link with the **GPL** variant.
If you really need the **GPL** mobile FFmpeg library, you must : 
- Use the Lite Flavor of Flutter Sound
- Link yourself your App with the library

**Comment by winsonloh1998** [comment]
I see, i did not know there is a Lite version available which without the ffmpeg. Thanks
