### ISSUE TITLE
[BUG]: cannot build app with 8.0.28 version

### ISSUE THREAD

**Issue by marcoberetta96** [Canardoux/tau#662]
## Flutter Sound Version : 8.0.28

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
```
|-- flutter_sound 8.0.28
|   |-- flutter_sound_platform_interface 8.0.28
|   |-- flutter_sound_web 8.0.28
|   |   |-- flutter_sound_platform_interface...

```
----------------------------------------------------------

## Severity

Cannot build my App

--------------------------------------------------------

## Platforms you faced the error 

- Android

------------------------------------------------

**Describe the bug**
Cannot build app with flutter_sound 8.0.28 version.
Build is ok for 8.0.2+1 version.

# Logs!!!!
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':flutter_sound:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':flutter_sound:debugCompileClasspath'.
   > Could not find xyz.canardoux:tau_sound_core:8.0.24.
     Required by:
         project :flutter_sound

```

Thank you!

**Comment by marcoberetta96** [comment]
Moreover, I see `Awaiting analysis to complete.` in this page [](https://pub.dev/packages/flutter_sound/score).

First time I see it, maybe it's just temporary.

**Comment by Larpoux** [comment]
I am very sorry. I am fighting today to build a new version published on Jitpack.
This is harder than expected.
Hopefully this will be fixed this evening.

Actually Flutter Sound is unavailable until fixed.
Sorry.

**Comment by Larpoux** [comment]
I will post something in this thread when Flutter Sound will be back

**Comment by marcoberetta96** [comment]
We will wait :)
Thank for your work!

**Comment by Larpoux** [comment]
Sorry Guys and Girls,

I am fighting with publishing tau_core on jit_pack.
This is absolutely necessary because jfrog/bintray  will close on May 1st, and we need to have another way to link Flutter Sound before this limit date. If not, nobody will be able to link their App anymore after May 1st.

Actually I am not successful and the link-edit does not work for Android.
I realize that it can be very bad for you not being able to use flutter Sound.

I hope to win this evening, but actually I am not very obtimist.
Thank you for your patience.

**Comment by Larpoux** [comment]
OK, Guys and Girls. I WIN  😄 .
Flutter Sound 8.1.1 is Released and Published on JitPack instead of Jfrog/bintray.

I hope everything OK now, and you can link correctly with Flutter Sound.
Please let me know if any problem.
Thank you for your patience.

**Comment by marcoberetta96** [comment]
Confirm, everything is working okay!
Thanks for your work!
