### ISSUE TITLE
[BUG]:   Undefined symbol: ___gxx_personality_v0

### ISSUE THREAD

**Issue by sm2017** [Canardoux/tau#666]
## Flutter Sound Version : 

- **FULL** or **LITE** flavor ?LITE

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```

```
|-- flutter_sound_lite 8.0.1+11
|   |-- flutter_sound_platform_interface 8.0.1+11
|   |-- flutter_sound_web 8.0.1+11
|   |   |-- flutter_sound_platform_interface...

```
----------------------------------------------------------

## Severity
Cannot build my App

--------------------------------------------------------

## Platforms you faced the error 

- iOS 
- Emulator 
- Real device

------------------------------------------------

**Describe the bug**
I  cannot run my app in iOS

**To Reproduce**
I just run the app and it returns error
----------------------------------------------

# Logs!!!!
(**This is very important**. Most of the time we cannot do anything if we do not have information on your bug)

```
Undefined symbols for architecture x86_64:
  "___gxx_personality_v0", referenced from:
      +[FlutterSound registerWithRegistrar:] in flutter_sound_lite(FlutterSound.o)
      +[FlutterSoundPlayerManager registerWithRegistrar:] in flutter_sound_lite(FlutterSoundPlayerManager.o)
      -[FlutterSoundPlayerManager init] in flutter_sound_lite(FlutterSoundPlayerManager.o)
      FlutterSoundPlayerReg(NSObject<FlutterPluginRegistrar>*) in flutter_sound_lite(FlutterSoundPlayerManager.o)
      -[FlutterSoundPlayerManager handleMethodCall:result:] in flutter_sound_lite(FlutterSoundPlayerManager.o)
      -[FlutterSoundPlayer startPlayerCompleted:duration:] in flutter_sound_lite(FlutterSoundPlayer.o)
      -[FlutterSoundPlayer needSomeFood:] in flutter_sound_lite(FlutterSoundPlayer.o)
      ...
ld: symbol(s) not found for architecture x86_64

```
-----------------------------------------------------------------

**Comment by sm2017** [comment]
https://github.com/Canardoux/tau/issues/483#issuecomment-707714716

**Comment by Amr1440** [comment]
How you solved this please @sm2017  ?

**Comment by zand-yasin** [comment]
add   -lc++

to your XCode > Runner > Target > Buld Settings > All > Linking > Other LInker Flags

just add and it does resolves your bug

**Comment by Akhu** [comment]
I had this problem too, thanks a LOT @zand-yasin !
How can this be closed :oo Why this even happen ? Somebody knows ? It's a problem on Flutter or this library ? :o We shouldn't have to add an obscure flag for iOS :/

**Comment by AbilucksanV2** [comment]
@zand-yasin Thankyou so much
<img width="563" alt="fix" src="https://user-images.githubusercontent.com/90438563/165690666-364d296a-c654-4ea1-abb0-9ca3bd63182e.png">
if any of you are wondering where to add the -lc++, here it is

**Comment by 12yanogden** [comment]
I added the -lc++ flag, but the issue persists
