### ISSUE TITLE
[ABNORMAL]: Size Apk too big?? Version flutter_sound: ^7.8.4 size apk 81MB

### ISSUE THREAD

**Issue by yusriltakeuchi** [Canardoux/tau#673]
I Install  this package with version flutter_sound: ^7.8.4

and i try to flutter build apk --release, then i got the apk size too big,
✓ Built build/app/outputs/flutter-apk/app-release.apk (81.7MB).

When i remove flutter sound, the apk size back to normal

**Comment by yusriltakeuchi** [comment]
Maybe someone can explain this?

**Comment by Larpoux** [comment]
I did not know that there was a limit in the APK size.
Could you try with the LITE flavor ?

Perhaps we should link without the video library ???

**Comment by yusriltakeuchi** [comment]
@Larpoux hi, i will post before and after apk size when i use flutter_sound

This is before i use flutter_sound, you can check in pubpsec.yaml i comment this package
<img width="909" alt="Screen Shot 2021-05-12 at 16 52 11" src="https://user-images.githubusercontent.com/10339660/117955749-8ecdd680-b342-11eb-984f-2e7094e42e34.png">

This is an after when i add flutter_sound in dependency
<img width="843" alt="Screen Shot 2021-05-12 at 16 54 06" src="https://user-images.githubusercontent.com/10339660/117955897-b58c0d00-b342-11eb-9adc-0be0e774538a.png">


you can see the apk size:
Before: 19.6MB
After: 81.7MB

**Comment by Larpoux** [comment]
This is because we link with Mobile FFmpeg .
You should try the LITE flavor of flutter sound.

**Comment by yusriltakeuchi** [comment]
> This is because we link with Mobile FFmpeg .
> You should try the LITE flavor of flutter sound.

What is the lite flavor? Which version?

**Comment by Larpoux** [comment]
flutter_sound_lite:  ^8.1.0

**Comment by yusriltakeuchi** [comment]
> flutter_sound_lite: ^8.1.0

Is that null safety version?

**Comment by Larpoux** [comment]
YES. 
If you do not want safety :
flutter_sound_lite: ^7.0.0

**Comment by yusriltakeuchi** [comment]
> YES.
> If you do not want safety :
> flutter_sound_lite: ^7.0.0

Thankyouuu, it’s work and back to normal size again. Bravo 💪

**Comment by mehrdad1990** [comment]
is there anyway to solve the issue with increased apk size. mine was around 30MB but now it is around 75MB using flutter_sound.
is there any configs we can use to reduce it using this library ?

**Comment by Larpoux** [comment]
There is no more LITE and FULL flavors.
Nowadays, Flutter Sound does not link with FFMPEG. So if there is a size problem, someone should investigate if something why this size is so much.
