### ISSUE TITLE
How to convert a .wav or .pcm to base64 string Flutter

### ISSUE THREAD

**Issue by pythonhubpy** [Canardoux/tau#704]
Converting a .wav file into a base64 format string.

This is how I record the audio and the audio is manually playable on my mobile phone and I can hear the recorded voice without any distortion.
```
  await _flutterSoundRecorder.startRecorder(
            codec: Codec.pcm16WAV,
            toFile: "${appDirectory.path}/recordedAudio${audiosPresent +
                1}.wav",
          );
```

Now I need to convert this .wav file into a base64 encoded string.
```

  final File recordedAudio = File(
              "/storage/emulated/0/MyAppDirectory/recordedAudio.wav");
          recordedAudio.openRead();
          final String audio = base64Encode(await recordedAudio.readAsBytes());
```

While I print the audio string I get all characters printed as "AAAAAAAAAAAAAAAAAAAAA" what is wrong in my code. How can I achieve this without any error?

Give a solution, please. Thanks in advance.

**Comment by mhstoller** [comment]
This is not related to Tau or the flutter_sound library, so it's better suited for StackOverflow.

That said, you don't need to call `openRead` if you're just going to call `readAsBytes` and await the value.

The second section of code uses the hardcoded path "/storage/emulated/0/Speakeasy/recordedAudio.wav". What is at that path? The recorded audio file has a path with an interpolated string, so it's different.

You should check the value of `recordedAudio.readAsBytes()` so you can see what is getting encoded to troubleshoot.

**Comment by pythonhubpy** [comment]
I think now the path will make sense.
Ok, will do that.
