### ISSUE TITLE
[BUG]: flutterSoundHelper.convertFile crash on release app

### ISSUE THREAD

**Issue by Necrometal** [Canardoux/tau#710]
## Flutter Sound Version : 

- **FULL**  flavor ?

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```

----------------------------------------------------------

## Severity

- Crash  on release app

--------------------------------------------------------

## Platforms you faced the error 

- Android 

- Real device 

------------------------------------------------

**Describe the bug**
On debug mode, i used flutterSoundHelper.convertFile to convert the temp file created by the recorder to permanent file;  i record on aac as temp and convert to premanent mp3; this work well on debug, but when i build a release app, record work well, but when on convert , the app crash, 
i said that is the convert the problem cause i put a specifi button to convert aac to mp3, and when the button clicked, the app crash,

----------------------------------------------

# Logs!!!!
i put some try catch on my code to see the output, this is the log on debug

I/flutter (14966): ----------------------------------------
I/flutter (14966): convert start
I/flutter (14966): ----------------------------------------
D/flutter-ffmpeg(14966): Running FFmpeg with arguments: [-loglevel, error, -y, -i, /data/user/0/com.example.topos/cache/300621-19#58-Bornage-Immatriculation.aac, /storage/emulated/0/Topos/300621-19#58-Bornage-Immatriculation.mp3].
I/mobile-ffmpeg(14966): Loading mobile-ffmpeg.
I/mobile-ffmpeg(14966): Loaded mobile-ffmpeg-full-arm64-v8a-4.4-lts-20200724.
D/mobile-ffmpeg(14966): Callback thread started.
D/flutter-ffmpeg(14966): FFmpeg exited with rc: 0
I/flutter (14966): ----------------------------------------
I/flutter (14966): convert end
I/flutter (14966): ----------------------------------------
-----------------------------------------------------------------

the aac file is the temp file, and the mp3 is the result of convert, the file is successfuly converted and it appear in the path where it would be. i don't know if this line "D/flutter-ffmpeg(14966): Running FFmpeg with arguments: [-loglevel, error, -y, -i, " mean something important or not cause this error text.

But on release this convert make the app crash.

Below screenshot of my full code to save the record

![Screenshot_3](https://user-images.githubusercontent.com/35568346/124001870-60c95200-d9d5-11eb-8b7d-9e1cee3cb10f.png)

**Comment by Larpoux** [comment]
I have no idea :(

Have you any possibility to check if your AAC file is correct before trying to convert it ?

**Comment by Necrometal** [comment]
> I have no idea :(
> 
> Have you any possibility to check if your AAC file is correct before trying to convert it on your release version ?

my device is not rooted, so i think i can't check manualy, but ill try with File.exist()

**Comment by Larpoux** [comment]
I am not an expert, but maybe you can try "adb pull ..."

**Comment by Necrometal** [comment]
> I am not an expert, but maybe you can try "adb pull ..."

adb pull with device connected or no need? 

i've tried to play the recorded (tmp file)on release and it work, make a dialog to show if file exit or not and it exist

**Comment by Larpoux** [comment]
ok. If you can play your AAC temporary file, it is certainly correct.

Actually I have no idea. 
Does someone else can help ?

**Comment by Larpoux** [comment]
Try to do a `convert` to an "xxx.opus" file.
Just to see if the crash is because .mp3.  (Mobile FFmpeg use `lame`  to encode mp3. But lame is not supposed to be in a released app).
I guess that you will get the same crash, but just try ...

**Comment by Necrometal** [comment]
> Try to do a `convert` to an "xxx.opus" file.
> Just to see if the crash is because .mp3. (Mobile FFmpeg use `lame` to encode mp3. But lame is not supposed to be in a released app).
> I guess that you will get the same crash, but just try ...

you mean opus extension?

**Comment by Larpoux** [comment]
yes

**Comment by Necrometal** [comment]
> yes

could you please give the exact code to make it? ^^" 
i just know Codec.aacADTS and Codec .mp3

**Comment by Larpoux** [comment]
😄

**Comment by Larpoux** [comment]
The extension really must be ".opus" instead of ".mp3" for your test.  FFmpeg uses the extension to select the correct output 
codec.

**Comment by Necrometal** [comment]
so tried to convert to obus using Codec.obusCAF and Codec.obusOGG, tried with aac to aac, all crash :(

**Comment by Larpoux** [comment]
:(

Did you try to connect your device to your computer and do a "flutter run --release" ?
We really need logs ...

**Comment by Necrometal** [comment]
at the last line, it crash
![Screenshot_4](https://user-images.githubusercontent.com/35568346/124014745-316e1180-d9e4-11eb-922e-93407d371c99.png)

**Comment by Larpoux** [comment]
Interesting.

Can you try to replace the special char "#" in your filename to something else ?

**Comment by Necrometal** [comment]
same thing
![Screenshot_5](https://user-images.githubusercontent.com/35568346/124015593-236cc080-d9e5-11eb-96da-2a7917f9d9ae.png)

**Comment by Larpoux** [comment]
The sequence seems incorrect : The player is paused and not stopped during the convert.

**Comment by Larpoux** [comment]
But this does not explain why a crash

**Comment by Larpoux** [comment]
The sequence is correct in your last logs.

I am stuck. No idea.

**Comment by Necrometal** [comment]
> I must study your log now.
> I I do not understand why there is a "pausePlayer()" before your convert.
> You should have a "stopPlayer()" and not a "pausePlayer()"
in this line i'm playing the record :/

**Comment by Larpoux** [comment]
Of course you use the full flavor of flutter sound, and not the lite ? don't you ?

**Comment by Necrometal** [comment]
> Of course you use the full flavor of flutter sound, and not the lite ? don't you ?

honestly i don't know .
i just use this [this](https://pub.dev/packages/flutter_sound/install)

**Comment by Larpoux** [comment]
What is the result of : 

flutter pub deps | grep flutter_sound

?

**Comment by Necrometal** [comment]
> What is the result of :
> 
> flutter pub deps | grep flutter_sound
> 
> ?

i'm using vscode, so i just copy the dependence on pubspec and it pub automaticly ^^"

**Comment by Larpoux** [comment]
Just check the command

flutter pub deps | grep flutter_sound

We will know which version flutter had selected

**Comment by Larpoux** [comment]
Or just : 
flutter pub deps

if you do not have a regular shell

**Comment by Necrometal** [comment]
i removed the dependence from pubspec and added it manually with flutter pub add flutter_sound

**Comment by Larpoux** [comment]
I insist you do a "flutter pub deps"  to be sure which flutter_sound version is selected

**Comment by Necrometal** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/35568346/124018765-7dbb5080-d9e8-11eb-8746-fc701411385b.png)

**Comment by Larpoux** [comment]
This is correct.

I am sorry, Necro, I am stuck.  Someone else can help ?

**Comment by Necrometal** [comment]
> This is correct.
> 
> I am sorry, Necro, I am stuck. Someone else can help ?

just a question , have you already use the converter on a little project? :) 
i think if you tried to make it yourself in little project can maybe help if its not a package bug :)

**Comment by mhstoller** [comment]
Might be better off using flutter sound lite and including ffmpeg as a separate dependency and running the commands directly.

Flutter_ffmpeg likes to crash or output weird things when multiple jobs are run concurrently. I had to create a queue system for ffmpeg calls to work around this. I'm sure there are other quirks and something like that could be causing this issue.

Best way forward is probably to run ffmpeg directly so you have full control over the process

**Comment by Larpoux** [comment]
I agree with @mhstoller.
Actually Flutter Sound Full  is linked with Flutter FFmpeg **FULL**. Flutter FFmpeg **FULL** is huge and probably you do not need all the video stuff. The current link of Flutter Sound Flull is a kind of hack to be able to play directly Opus files on iOS.

If you use Flutter Sound Lite and put a dependency on "Flutter FFmpeg Audio" (or maybe even a lighter library),
you will have something more clean and more lite.

**Comment by Larpoux** [comment]
@mhstoller : 

I am not surprised that you got some concurrency issues using Flutter Ffmpeg.
All the Flutter Sound verbs are protected with an interlock semaphore.
But I did not realized that `Convert()` must be also protected with this interlock semaphore.

Someone (me?) should add a few lines of code to achieve that.

**Comment by Larpoux** [comment]
> just a question , have you already use the converter on a little project? :)
> i think if you tried to make it yourself in little project can maybe help if its not a package bug :)

Yes. Definitely. I began to write several few very simple test app. The purpose of those little test are to show and test only one or two Flutter Sound feature.
We must code a new very little test for the Convert routine.

**Comment by Necrometal** [comment]
> > just a question , have you already use the converter on a little project? :)
> > i think if you tried to make it yourself in little project can maybe help if its not a package bug :)
> 
> Yes. Definitely. I began to write several few very simple test app. The purpose of those little tests are to show and test only one or two Flutter Sound feature at a time.
> We must code a new very little test for the Convert routine.
> 
> @Necrometal :
> I will do some tests and fix concurrency issues if any, tomorrow.
> Please wait a few days.
> I am sorry that you get problems with Flutter Sound.

Not problem dude :) for moment i used to record the sound directly on perment file xD
But record an mp3 is not allowed right? i tried on record to mp3 but no sound when playing the file.

**Comment by Necrometal** [comment]
> Might be better off using flutter sound lite and including ffmpeg as a separate dependency and running the commands directly.
> 
> Flutter_ffmpeg likes to crash or output weird things when multiple jobs are run concurrently. I had to create a queue system for ffmpeg calls to work around this. I'm sure there are other quirks and something like that could be causing this issue.
> 
> Best way forward is probably to run ffmpeg directly so you have full control over the process

Have you please any tutorial for doing the FFmpeg separately?

**Comment by Larpoux** [comment]
Yes. Android and iOS does not allow us to record mp3.
What you are trying to do is correct : record AAC (for example) and then do a convert to mp3 with ffmpeg.

I am writing a little test for Convert. I will tell you when done.

**Comment by Larpoux** [comment]
> Have you please any tutorial for doing the FFmpeg separately?

The documentation is on the _Flutter FFmpeg_ site.
You must add a dependency to Flutter_FFmpeg  and you must link your android App with Mobile FFmpeg.
I think that this link is not obvious. It is the reason for which I linked Flutter Sound to Fluttter FFmpeg, so that Flutter Sound users does not bother with that.

**Comment by Larpoux** [comment]
Wait until tomorrow. I will have a new Flutter Sound with an example of Convert AAC to MP3.

**Comment by Necrometal** [comment]
> Wait until tomorrow. I will have a new Flutter Sound with an example of Convert AAC to MP3.

ok thanks :)

**Comment by Larpoux** [comment]
Is there any reason you try to convert during a PausePlayer() ?

**Comment by Necrometal** [comment]
> Is there any reason you try to convert during a PausePlayer() ?

Not at all, i just use my app like guest user xD, i just paused the audio for no reason and save (convert) like nothing happen

**Comment by Larpoux** [comment]
OK. I will keep my example very simple : 
- Convert an AAC file to MP3
- Play the MP3

**Comment by Necrometal** [comment]
so the sound must be stopped to be converted?

**Comment by Larpoux** [comment]
No.
I just asked to be similar in my test with your App

**Comment by Necrometal** [comment]
> No.
> I just asked to be similar in my test with your App

okay, i'll wait for your up tomorrow

**Comment by Larpoux** [comment]
Necro,
I am able to reproduce your issue on my development environment.

The problem is a problem in Mobile FFmpeg : [Here](https://github.com/tanersener/mobile-ffmpeg/issues/616)
@tanersener published a work-around. I am going to try this work-around this afternoon.

Then I will post more informations in this thread.

**Comment by Larpoux** [comment]
Hi Necro,

Flutter Sound 8.1.9 is released.
This version has a fix for your issue.
You must also check your build.gradle : 

- Remove any reference to repository `jcenter()`
- Add a reference to `mavenCentral()` if not already done

I wrote a very simple example [here](https://github.com/Canardoux/tau/blob/master/flutter_sound/example/lib/convert_to_mp3/convert_to_mp3.dart) that record an AAC audio, convert it to MP3 and playback it.
You probably do not need any more this example : your code was correct and the problem was on Flutter FFmpeg.

Thank you for your patience

**Comment by Necrometal** [comment]
> Hi Necro,
> 
> Flutter Sound 8.1.9 is released.
> This version has a fix for your issue.
> 
> You must also check your build.gradle :
> 
> * Remove any reference to repository `jcenter()`
> * Add a reference to `mavenCentral()` if not already done
> 
> I wrote a very simple example [here](https://github.com/Canardoux/tau/blob/master/flutter_sound/example/lib/convert_to_mp3/convert_to_mp3.dart) that record an AAC audio, convert it to MP3 and playback it.
> You probably do not need any more this example : your code was correct and the problem was on Flutter FFmpeg.
> 
> Thank you for your patience

Thanks :)

**Comment by Necrometal** [comment]
it work on flutter run --release, i think it'll work on build release too :) thanks.

i have another thing to ask if you can check [this one](https://github.com/Canardoux/tau/issues/712) please ^^

**Comment by jack0-0wu** [comment]
> > Hi Necro,
> > Flutter Sound 8.1.9 is released.
> > This version has a fix for your issue.
> > You must also check your build.gradle :
> > 
> > * Remove any reference to repository `jcenter()`
> > * Add a reference to `mavenCentral()` if not already done
> > 
> > I wrote a very simple example [here](https://github.com/Canardoux/tau/blob/master/flutter_sound/example/lib/convert_to_mp3/convert_to_mp3.dart) that record an AAC audio, convert it to MP3 and playback it.
> > You probably do not need any more this example : your code was correct and the problem was on Flutter FFmpeg.
> > Thank you for your patience
> 
> Thanks :) i'll test it and give you a feedback

good job.
