### ISSUE TITLE
[BUG]: Can't record with codec MP3

### ISSUE THREAD

**Issue by yusriltakeuchi** [Canardoux/tau#717]
I try to record audio using mp3 file, but in console showing error **_CodecNotSupportedException**.

This is my code when start recording

```dart
_mRecorder.startRecorder(
    codec: Codec.mp3,
    toFile: path,
    bitRate: 320000, /// 320Kbps
    sampleRate: 96000
  );
```

**Comment by Larpoux** [comment]
We cannot record MP3 (Codec not supported).
If you must record MP3 you can use a supported codec, an then convert the file to MP3.

See the example included with Flutter Sound

**Comment by yusriltakeuchi** [comment]
> We cannot record MP3 (Codec not supported).
> If you must record MP3 you can use a supported codec, an then convert the file to MP3.
> 
> See the example included with Flutter Sound

Okay, thanks for the answer

**Comment by shobith10** [comment]
how to convert that file to MP3

**Comment by Larpoux** [comment]
It is very simple.
You can use the FFmpeg Kit plugin.
Converting a file from one codec to another one is just a matter of calling the API verb of FFmeg
