### ISSUE TITLE
Remove constant log message while audio player active. 

### ISSUE THREAD

**Issue by Chappie74** [Canardoux/tau#718]
**Is your feature request related to a problem? Please describe.**
While the audio player is active/paused, it seems there's  a constant log message that occurs while the PlaybackDisposition stream is active. For me it's really annoying especially when I'm trying to debug and read my own log messages. <br>
![image](https://user-images.githubusercontent.com/21108487/124937037-06cc1c00-dfd5-11eb-9a89-5e4a11f5c79e.png)
<br>

**Describe the solution you'd like**
A simple removal of the print/log statement would be enough. <br>
![image](https://user-images.githubusercontent.com/21108487/124937256-367b2400-dfd5-11eb-9ab9-19e7e2389c4a.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by davidAg9** [comment]
this should probably be enabled in debug 
....its still a good feature under the package

**Comment by Larpoux** [comment]
I am currently working on an implementation of a Logger.
The app developer will be able to choose the level of the Flutter Sound logs.

I will finish this task in a few days.

**Comment by Chappie74** [comment]
Thanks, appreciate it. Keep up the hard work.

**Comment by Larpoux** [comment]
This is fixed in v.8.2.0.

Please re-open this issue if you have still problems
