### ISSUE TITLE
Problem recording on Samsung devices

### ISSUE THREAD

**Issue by arturopn** [Canardoux/tau#726]
Hi on SDK 29 the recorder doesnt start on samsung devices, i have tried on 2, on any other device is working perfectly.

I read something about samsung changing some permissions on sdk 28 or 29, have any of you had a problem?

**Comment by mhstoller** [comment]
Can we see your code that you use to open the audio session and start the recorder?

I don't have a Samsung device to test on

**Comment by arturopn** [comment]
of course thanks for the reply 

 Future<void> openTheRecorder() async {
    if (!kIsWeb) {
      var status = await Permission.microphone.request();
      if (status != PermissionStatus.granted) {
        throw RecordingPermissionException('Microphone permission not granted');
      }
    }
    await _mRecorder.openAudioSession();
    _mRecorderIsInitiated = true;
    setState(() => hasMicPermission = true);
  }

  // ----------------------  Here is the code for recording and playback -------

  void record() async {
    _mPath = "${DateTime.now().millisecondsSinceEpoch.toString()}.aac";
    _mRecorder
        .startRecorder(
      toFile: _mPath,
      sampleRate: 44000,
      codec: Codec.aacADTS,
    )
        .then((value) {
      setState(() {});
    });
  }

**Comment by Larpoux** [comment]
I do not know any problem on Samsung devices.

Please provide the missing informations and re-open this issue : 
- Result of "flutter pub deps | grep flutter_sound
- YOUR LOGS !!! with `(logLevel: debug)`
