### ISSUE TITLE
App crashes in release mode when estimating the duration of audio file

### ISSUE THREAD

**Issue by mkassir95** [Canardoux/tau#731]
I am trying to estimate the duration of audio file before playing it  
The app crashes  in release mode  when I use flutter sound helper to estimate the duration of audio file .
This is an example of my code : Duration duration = await flutterSoundHelper.duration(filePath);
It works fine in debug mode , while the app crashes in release mode and if the above line is commented , things go well
I am using the latest version of flutter sound  version 8.2.0

**Comment by Larpoux** [comment]
Please, provide the missing informations and re-open this issue : 
- Result of `flutter pub deps | grep flutter_sound`
- ios, android or web
- YOUR LOGS !!! (after setting the Log Level to `Level.debug`
