### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by 726D** [Canardoux/tau#734]
## Flutter Sound Version : 8.2.5
- **FULL** 
- flutter_sound 8.2.5

----------------------------------------------------------

## Severity

- Cannot build my App 

In
`flutter_sound/lib/flutter_sound.dart`
the former  
`export 'public/util/log.dart';`
was changed into 
`export 'package:logger/logger.dart' show Level, Logger;`
causing a conflict when using the dart logging package 

--------------------------------------------------------

## Platforms you faced the error 

- iOS 
- Android 
- Emulator 
- Real device 

------------------------------------------------

**Describe the bug**

In
`flutter_sound/lib/flutter_sound.dart`
the former  
`export 'public/util/log.dart';`
was changed into 
`export 'package:logger/logger.dart' show Level, Logger;`
causing a conflict when using the dart logging package as Logger gets defined double

----------------------------------------------

# Logs

no build -> no run log
-----------------------------------------------------------------

**Comment by Larpoux** [comment]
Not good 👎 

The trace/logs are now handled by Logger plugin.
Probably it was not a good idea to export Level and Logger in flutter_sound.

I will fix that soon.
But actually I am in the process of developing some new functionnalités and the master branch is unstable.
If possible, I would prefer not to create a branch just to fix your issue.

Are you blocked by this issue ?

**Comment by Larpoux** [comment]
I will try to fix that tomorrow ...

**Comment by 726D** [comment]
i can work around, take your time

**Comment by Larpoux** [comment]
[Flutter Sound 8.3.4](https://tau.canardoux.xyz/changelog.html) is released.

There is no more any export of the Logger used by τ.

Please re-open this issue if you still have problems.
