### ISSUE TITLE
Using flutter_ffmpeg plugin  with flutter_sound plugin  results in  duplicate dependences 

### ISSUE THREAD

**Issue by mkassir95** [Canardoux/tau#736]
I am using  the following  plugins :
 1-  flutter_sound: ^8.1.4  to record and play voices
 2-  flutter_ffmpeg:  ^0.4.0  to concatenate three wave files in one single file

The result appearing  in the log is :  
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.arthenica.mobileffmpeg.Abi found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.AbiDetect found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.AsyncFFmpegExecuteTask found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.AsyncFFprobeExecuteTask found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.AsyncGetMediaInformationTask found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.BuildConfig found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.CameraSupport found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.Config found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.Config$1 found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.ExecuteCallback found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.FFmpeg found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.FFmpegExecution found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.FFprobe found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.GetMediaInformationCallback found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.Level found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.LogCallback found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.LogMessage found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.MediaInformation found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.MediaInformationParser found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.Packages found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.Signal found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.Statistics found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.StatisticsCallback found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.StreamInformation found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.util.Pair found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)
  Duplicate class com.arthenica.mobileffmpeg.util.Trio found in modules jetified-mobile-ffmpeg-full-4.4.LTS-runtime.jar (com.arthenica:mobile-ffmpeg-full:4.4.LTS) and jetified-mobile-ffmpeg-https-4.4-runtime.jar (com.arthenica:mobile-ffmpeg-https:4.4)

**Comment by Larpoux** [comment]
You must link with FlutterSound LITE,
not FlutterSound FULL

**Comment by Larpoux** [comment]
You [can read this](https://tau.canardoux.xyz/guides_lite-full.html)

Please, re-open your issue if you have problems using the LITE flavor of Flutter Sound
