### ISSUE TITLE
[BUG]:Crash when play from stream, if not data feed 

### ISSUE THREAD

**Issue by ipconfiger** [Canardoux/tau#773]
## Flutter Sound Version : 8.3.9

- **FULL** or **LITE** flavor ? LITE

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```

----------------------------------------------------------

## Severity

- Crash ? yes

- Result is not what expected ?

- Cannot build my App ? no

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ? yes

- Android ?

- Flutter Web ?

- Emulator ? 

- Real device ? yes

------------------------------------------------

**Describe the bug**

**To Reproduce**
1. Play from stream
2. wait ....
3. See error
----------------------------------------------

# Logs!!!!
(**This is very important**. Most of the time we cannot do anything if we do not have information on your bug).
To activate the logs, you must instantiate your modules with the Log Level set to `Level.debug` :
```
if (_playerModule == null) {
      _playerModule = FlutterSoundPlayer();
    }
    debugPrint('有人调用了Play');
    await _playerModule.openAudioSession(
      withUI: false,
      mode: _sessionMode,
      category: SessionCategory.playAndRecord,
      device: device,
    );
    await _playerModule.setVolume(1);
    await _playerModule.startPlayerFromStream(sampleRate: tSampleRate);
    _canPlay = true;
    _playChecker = Timer.periodic(Duration(milliseconds: 2), (timer) {
      if (!_playing) {
        playQueue();
      }
    });
```
See [this](https://tau.canardoux.xyz/logger.html)

Assertion failed: (waitingBlock == nil), function -[AudioEngine feed:], file FlautoPlayerEngine.mm, line 341.
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001af8ee7b0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1af8ee7b0 <+8>:  b.lo   0x1af8ee7cc               ; <+36>
    0x1af8ee7b4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1af8ee7b8 <+16>: mov    x29, sp
    0x1af8ee7bc <+20>: bl     0x1af8cb1fc               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
You are trying to send something every 2 milliseconds.
You overflow the buffers.
Please, look to the two examples : 

- live_playback_with_back_pressure.dart
- live_playback_without_back_pressure.dart
